http://ftpmirror.uk/pub/Software/vSphere/v7.0/
https://www.tvpartstoday.com
https://liujiacai.net/blog/2022/04/30/modern-c/
/etc/sysctl.d/sysctl.conf kernel.printk = 3 4 1 4
https://hdqwalls.com/
https://zimuku.org
https://www.pexels.com/

find . -type f -name "*.mp4" -exec ffmpeg -ss 00:00:23 -i {} -c copy {}.mp4 \;
find . -type f -name "*.mp4" -exec ffmpeg -i {} -threads 12 -preset ultrafast -vf "delogo=x=1690:y=700:w=229:h=99:enable='between(t,00,15)'" {}.mp4 \;
ffmpeg -i *.mp4 sample.jpg -ss 00:00:05  -r 1 -vframes 1 -an -vcodec mjpeg 
